Add support for external drag & drop to the initial screen
oss-review-toolkit/ort-workbench pull request #119
Opened 2023-05-10 09:36 UTC by sschuberth

Resolves #65.

2023-05-10 09:36 UTC, sschuberth commented on src/main/kotlin/ui/App.kt
> +                        runCatching { controller.openOrtResult(files.first()) }
@mnonnenmacher, can we discuss the refactoring needed to pass multiple files here?

2023-05-13 16:35 UTC, mnonnenmacher commented on src/main/kotlin/ui/App.kt
> +                        runCatching { controller.openOrtResult(files.first()) }
What is the use case, do you want to drag multiple files at once to the workbench?

2023-05-13 16:39 UTC, mnonnenmacher commented on src/main/kotlin/ui/App.kt
> +                        runCatching { controller.openOrtResult(files.first()) }
Ok, I haven't looked at the code before writing the previous comment. Why not do `files.forEach { controller.openOrtResult(it) }`?

Also, you should add `val scope = rememberCoroutineScope()` to the top of the function and use `scope.launch { ... }` here instead of `runBlocking`.

2023-05-13 16:40 UTC, mnonnenmacher commented on src/main/kotlin/ui/App.kt
> +                        runCatching { controller.openOrtResult(files.first()) }
Btw, error handling in case the ORT result file cannot be read is currently broken (it doesn't show the error correctly). I will create a separate PR for this so you should not have to care if all files in the list are valid ORT result files.

2023-05-13 16:48 UTC, mnonnenmacher commented on src/main/kotlin/ui/WorkbenchController.kt
> +        if (newOrtModel.state.value !in listOf(OrtApiState.LOADING_RESULT, OrtApiState.PROCESSING_RESULT)) {
I think this if condition should not be required, it can probably also be removed from the function above but I haven't tested it yet.

2023-05-13 16:52 UTC, mnonnenmacher commented on src/main/kotlin/ui/WorkbenchController.kt
> +                _ortModels.value = _ortModels.value + newOrtModel
The old `loadResultFunction` could not be called multiple times in parallel because it could only be triggered by the user if no file dialog is currently shown. However, if this is called in a loop it could lead to race conditions. It's probably good to surround this with `mutex.withLock {}` to ensure that `_ortModels.value` is always up to date.

2023-05-14 10:54 UTC, sschuberth commented on src/main/kotlin/ui/App.kt
> +                        runCatching { controller.openOrtResult(files.first()) }
> What is the use case, do you want to drag multiple files at once to the workbench?

Yes.

> Why not do `files.forEach { controller.openOrtResult(it) }`?

I was hesitant to do so as the check on `newOrtModel.state.value` in `openOrtResult` didn't look to me like that would work.

> Also, you should add `val scope = rememberCoroutineScope()` to the top of the function and use `scope.launch { ... }` here instead of `runCatching`.

Thanks, that was a missing bit.

2023-05-14 11:04 UTC, sschuberth commented on src/main/kotlin/ui/WorkbenchController.kt
> +        if (newOrtModel.state.value !in listOf(OrtApiState.LOADING_RESULT, OrtApiState.PROCESSING_RESULT)) {
I've removed it in my copy of the function, and it seems to work. Still need to test (on Windows) if the check can also be removed from the original function.

2023-05-14 13:10 UTC, mnonnenmacher requested changes

2023-05-14 13:10 UTC, mnonnenmacher commented on src/main/kotlin/ui/App.kt
> +            ),
How about we move this up to the `Surface` in line 71? If the modifier works for a surface users could also open files by drag & drop if another file is already loaded.

2023-05-14 13:10 UTC, mnonnenmacher commented on src/main/kotlin/ui/WorkbenchController.kt
> +            _ortModels.value = mutex.withLock { _ortModels.value + newOrtModel }
I wondering if this could still cause a race condition because the assignment itself is not locked. Maybe do `mutex.withLock { _ortModels.value = _ortModels.value + newOrtModel }` to be on the safe side.

2023-05-14 13:28 UTC, sschuberth commented on src/main/kotlin/ui/WorkbenchController.kt
> +            _ortModels.value = mutex.withLock { _ortModels.value + newOrtModel }
> I wondering if this could still cause a race condition because the assignment itself is not locked.

I'm pretty sure that assignments are atomic, so I don't believe this to be a problem. The current form IMO reads nicer (and `withLock` must have a return value for a reason), so if we can, I'd prefer to keep it.

2023-05-14 13:42 UTC, sschuberth commented on src/main/kotlin/ui/App.kt
> +            ),
Makes sense, but I can't get the dynamic background coloring to work then when dragging...

2023-05-14 13:58 UTC, sschuberth commented on src/main/kotlin/ui/App.kt
> +            ),
Got it working 😄

2023-05-14 14:24 UTC, mnonnenmacher approved these changes

2023-05-14 14:24 UTC, merged