Miscellaneous small Gradle / detekt improvements
oss-review-toolkit/ort-workbench pull request #12
Opened 2022-02-06 18:25 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2022-02-06 21:08 UTC, mnonnenmacher requested changes

2022-02-06 21:08 UTC, mnonnenmacher commented on README.md
> +A basic workbench for [ORT](https://ossreviewtoolkit.org) result files, implemented with
Unfortunately this link doesn't work.

2022-02-07 06:30 UTC, sschuberth commented on README.md
> +A basic workbench for [ORT](https://ossreviewtoolkit.org) result files, implemented with
Ah, right, we had enabled HTTPS only for the dashed version of the domain. Will change.

2022-02-07 07:36 UTC, mnonnenmacher commented on README.md
> +A basic workbench for [ORT](https://ossreviewtoolkit.org) result files, implemented with
This link causes SSL_ERROR_BAD_CERT_DOMAIN because the certificate does not match the domain. I think we should stick with HTTP or directly link to GitHub until this is fixed. I have created https://github.com/oss-review-toolkit/ort-governance/issues/24.

2022-02-07 08:28 UTC, sschuberth commented on README.md
> +A basic workbench for [ORT](https://ossreviewtoolkit.org) result files, implemented with
> This link causes SSL_ERROR_BAD_CERT_DOMAIN

That's fixed now.

2022-02-07 14:50 UTC, mnonnenmacher approved these changes

2022-02-07 14:51 UTC, merged