feat: Redesign the summary page
oss-review-toolkit/ort-workbench pull request #164
Opened 2023-10-03 13:26 UTC by mnonnenmacher

Change the summary page to show detailed information about the executed ORT tools and the result file.

Fixes #111.

2023-10-04 09:19 UTC, sschuberth requested changes

2023-10-04 09:19 UTC, sschuberth commented on src/main/kotlin/model/OrtApi.kt
> +        } ?: ScannerStats(emptyMap())
Use `ScannerStats.EMPTY`.

2023-10-04 09:19 UTC, sschuberth commented on src/main/kotlin/model/OrtApi.kt
> +        hints = count { it.severity == Severity.HINT },
Consider using `groupingBy` / `eachCount` to iterate over the list fewer times.

2023-10-04 09:19 UTC, sschuberth commented on src/main/kotlin/model/OrtApi.kt
> +        hints = count { it.severity == Severity.HINT },
Consider using `groupingBy` / `eachCount` to iterate over the list fewer times.

2023-10-04 09:19 UTC, sschuberth commented on src/main/kotlin/ui/summary/AdvisorInfoCard.kt
> +                    "NPM" to "9.4.0"
IMO an entry here is not realistic for the advisor. Can we simply leave it empty?

2023-10-04 09:19 UTC, sschuberth commented on src/main/kotlin/ui/summary/AdvisorInfoCard.kt
> +                    "NPM" to "9.4.0"
Or extract common "dummy" values to constants and also use them in `AnalyzerInfo` etc?

2023-10-04 09:19 UTC, sschuberth commented on src/main/kotlin/ui/summary/ResultFileInfoCard.kt
> +                        "Size" to "${info.size / KIBI} kb",
Maybe a bit of "cheating", but I guess we could use ORT's extension function like `/ 1.kibibytes` here.

2023-10-04 09:19 UTC, sschuberth commented on src/main/kotlin/ui/summary/ResultFileInfoCard.kt
> +                size = 1024 * 1024,
`1.mebibytes`?

2023-10-04 09:19 UTC, sschuberth commented on src/main/kotlin/ui/summary/SummaryState.kt
> +        val EMPTY = ResultFileInfo("", 0L, Instant.now(), VcsInfo.EMPTY, emptyMap(), RepositoryConfigurationStats.EMPTY)
For an empty object, should it rather use `Instant.EPOCH`?

2023-10-04 09:19 UTC, sschuberth commented on src/main/kotlin/ui/summary/SummaryState.kt
> +interface ToolInfo {
Could this be an abstract class to avoid re-declaring properties in derived classes?

2023-10-04 09:19 UTC, sschuberth commented on src/main/kotlin/utils/Extensions.kt
> + * Remove the first line that reads "---" when serializing YAML with Jackson.
Could we make use of `.disable(YAMLGenerator.Feature.WRITE_DOC_START_MARKER)` instead?

2023-10-04 20:45 UTC, mnonnenmacher commented on src/main/kotlin/model/OrtApi.kt
> +                    .filterKeys { it != null }.mapValues { it.value.size } as Map<LicenseSource, Int>,
I went with this instead because it is a bit shorter and I wasn't sure if `filterIsInstance` works as expected with nested generics:
```kotlin
.entries.mapNotNull { (key, value) -> key?.let { key to value.size } }.toMap()
```

2023-10-04 21:14 UTC, mnonnenmacher commented on src/main/kotlin/model/OrtApi.kt
> +                    dependencyCount = projects.sumOf { dependencyCounts[it.id] ?: 0 }
I made a dedicated `getOrZero` helper function for this, it could be used in more places in a separate change.

2023-10-04 21:15 UTC, mnonnenmacher commented on src/main/kotlin/ui/summary/AdvisorInfoCard.kt
> +                    "NPM" to "9.4.0"
For the previews I don't care that much if the values make sense as long as it populates the UI properly. And I'd rather have it in place, this makes it easier to verify that the preview shows the correct data.

2023-10-04 21:16 UTC, mnonnenmacher commented on src/main/kotlin/ui/summary/ResultFileInfoCard.kt
> +                        "Size" to "${info.size / KIBI} kb",
This would require adding an explicit dependency on common-utils so I'd rather reconsider this later if there are more use cases.

2023-10-04 21:16 UTC, mnonnenmacher commented on src/main/kotlin/ui/summary/ResultFileInfoCard.kt
> +                size = 1024 * 1024,
See above.

2023-10-04 21:17 UTC, mnonnenmacher commented on src/main/kotlin/utils/Extensions.kt
> + * Remove the first line that reads "---" when serializing YAML with Jackson.
I have added a TODO comment, I don't want to deal with copying the `yamlMapper` in this change.

2023-10-04 21:18 UTC, mnonnenmacher commented on src/main/kotlin/ui/summary/SummaryState.kt
> +interface ToolInfo {
The data class constructors would still need those parameters to pass them to the constructor of the abstract class, so in the end it would be more verbose.

2023-10-05 06:02 UTC, sschuberth commented on src/main/kotlin/ui/summary/ResultFileInfoCard.kt
> +                size = 1024 * 1024,
> if there are more use cases.

This is one more use case 😜 Just kidding; let's leave it as-is.

2023-10-05 06:03 UTC, sschuberth approved these changes

2023-10-05 10:41 UTC, merged