Miscellaneous improvements
oss-review-toolkit/ort-workbench pull request #173
Opened 2023-10-13 14:54 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2023-10-14 07:32 UTC, fviernau approved these changes

2023-10-15 08:43 UTC, sschuberth commented
@mnonnenmacher is this also ok with you? In Particular, I wonder whether

https://github.com/oss-review-toolkit/ort-workbench/pull/173/files#diff-2f2376c0396f630c4a0333ba05dd78ff1bec1bdaab8dd9b580e854f306edb437R79-R81

could be simplified now that the string representation of `info.duration` is used directly.

2023-10-15 09:19 UTC, mnonnenmacher requested changes

2023-10-15 09:19 UTC, mnonnenmacher commented on src/main/kotlin/ui/summary/ScannerInfoCard.kt
> +                          Detected $detectedLicenseCount licenses and $detectedLicenseCount copyrights in
Second variable should be `detectedCopyrightCount`.

2023-10-15 09:19 UTC, mnonnenmacher commented on src/main/kotlin/ui/summary/ScannerInfoCard.kt
> +                                ScannerWrapperStats(1, 2, 3, 4, 4),
I have used different values so that you can see in the preview if they are used in the right place. This would have made above bug visible in the preview.

2023-10-15 09:19 UTC, mnonnenmacher commented on src/main/kotlin/ui/summary/ToolInfoCard.kt
> +                        info.duration.toString()
Could this be a one-liner now?

2023-10-15 09:26 UTC, mnonnenmacher commented
> @mnonnenmacher is this also ok with you? In Particular, I wonder whether
> 
> https://github.com/oss-review-toolkit/ort-workbench/pull/173/files#diff-2f2376c0396f630c4a0333ba05dd78ff1bec1bdaab8dd9b580e854f306edb437R79-R81
> 
> could be simplified now that the string representation of `info.duration` is used directly.

Do you mean if `remember` is still required? Compared to the code before I would say yes, because `duration.toString()` should be on the same level of complexity as the previous code. In general, I don't know if there is a good rule for when a calculation becomes complex enough to be remembered across recompositions, so I tend to use it whenever something is more complex than simple math or a string concatenation.

2023-10-15 17:25 UTC, sschuberth commented
> Do you mean if `remember` is still required?

Yes. Thanks for the explanation.

2023-10-15 17:49 UTC, mnonnenmacher approved these changes

2023-10-15 17:49 UTC, merged