Add initial `CODEOWNERS` / `.mailmap` files
oss-review-toolkit/ort-workbench pull request #27
Opened 2022-02-24 19:51 UTC by sschuberth

Please have a look at the individual commit messages for the details.

2022-02-25 16:51 UTC, mnonnenmacher requested changes

2022-02-25 16:51 UTC, mnonnenmacher commented on .github/CODEOWNERS
> +* @oss-review-toolkit/kotlin-devs
GitHub complains that this owner is unknown, is this a false alarm?

2022-02-25 16:51 UTC, mnonnenmacher commented on .mailmap
> +Martin Nonnenmacher <martin.nonnenmacher@bosch.io> <martin.nonnenmacher@here.com>
Should be "gmail.com" instead of "here.com".

2022-02-25 20:19 UTC, sschuberth commented on .github/CODEOWNERS
> +* @oss-review-toolkit/kotlin-devs
There probably was some glitch, as previously I also could not choose `@oss-review-toolkit/kotlin-devs` manually from the "Reviewers" menu, but it seems to be resolved now. Let's just see if this works once merged.

2022-02-25 20:22 UTC, sschuberth commented on .github/CODEOWNERS
> +* @oss-review-toolkit/kotlin-devs
Correction, there indeed was a permission issue that I just fixed.

2022-02-27 16:13 UTC, mnonnenmacher approved these changes

2022-02-27 16:13 UTC, merged